/* ================================================================
   Academic Advising Database  —  Full Schema
   ================================================================ */

/* ---------- Bootstrap: pgvector -------------------------------- */
-- Run outside a transaction block so it never dead-locks
CREATE EXTENSION IF NOT EXISTS vector;

/* ---------- ❶ LOOKUPS ------------------------------------------ */

CREATE TABLE IF NOT EXISTS Category (
    category_id   VARCHAR(16) PRIMARY KEY,         -- 'CS', 'DS', 'SWE', ...
    name          TEXT        NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Skills (
    skill_id          SERIAL PRIMARY KEY,
    skill_name        TEXT NOT NULL UNIQUE,
    skill_description TEXT,
    skill_category    VARCHAR(64)
);

/* ---------- ❷ CORE ENTITIES ------------------------------------ */

/* 2-A  Major / Program hierarchy */
CREATE TABLE IF NOT EXISTS Majors (                   
    major_id     VARCHAR(32) PRIMARY KEY,   -- 'CS', 'DS', ...
    major_name   TEXT        NOT NULL,
    department   VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS Program_Offerings (         
    program_id       VARCHAR(16) PRIMARY KEY,
    major_id         VARCHAR(32) REFERENCES Majors(major_id) ON DELETE CASCADE,
    degree_level     VARCHAR(16) NOT NULL,         -- 'B.S.', 'M.S.', 'Ph.D.'
    prerequisites    TEXT,
    description      TEXT,
    program_url      TEXT,
    is_active        BOOLEAN DEFAULT TRUE,          -- was is_available
    program_name     TEXT,
    effective_since  DATE
);

/* 2-B  Courses */
CREATE TABLE IF NOT EXISTS Courses (
    course_id          VARCHAR(16) PRIMARY KEY,      -- 'CAP 2757'       
    course_title       TEXT NOT NULL,
    syllabus_text      TEXT,
    prerequisites      TEXT,
    credits            INT,
    department         VARCHAR(128),
    level              VARCHAR(8),                 -- 'UG','G'
    semester_offered   VARCHAR(16),
    course_description TEXT,
    faculty_email      TEXT,
    course_url         TEXT,
    capacity           INT,
    last_updated       TIMESTAMPTZ DEFAULT now(),
    outcomes           TEXT,
    embedding          vector(384)
);

/* 2-C  Job postings */
CREATE TABLE IF NOT EXISTS Job_Postings (
    job_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer         TEXT NOT NULL,
    job_title        TEXT NOT NULL,
    location         TEXT,
    job_description  TEXT,
    job_url          TEXT,
    posting_date     TIMESTAMPTZ,
    expiration_date  TIMESTAMPTZ,
    job_type         VARCHAR(64),
    min_salary       NUMERIC,
    max_salary       NUMERIC,
    currency         VARCHAR(8),
    category_id      VARCHAR(16) REFERENCES Category(category_id) ON DELETE SET NULL,
    embedding        vector(384)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_job_postings_job_url ON Job_Postings(job_url);
CREATE INDEX IF NOT EXISTS idx_job_postings_category       ON Job_Postings(category_id);

/* 2-D  People */
CREATE TABLE IF NOT EXISTS Users_Students (
    user_id        INT PRIMARY KEY,
    first_name     VARCHAR(64),
    last_name      VARCHAR(64),
    email          TEXT UNIQUE,
    status         VARCHAR(32),                    -- 'active','alumni',...
    career_interest TEXT,
    password_hash   TEXT                           -- for auth if needed
);

CREATE TABLE IF NOT EXISTS Faculty (
    faculty_email    TEXT PRIMARY KEY,
    full_name        TEXT NOT NULL,
    department       VARCHAR(128),
    title            VARCHAR(128),
    office_location  VARCHAR(128),
    phone_number     VARCHAR(32),
    website          TEXT
);

CREATE TABLE IF NOT EXISTS Academic_Advisor (
    advisor_email     TEXT PRIMARY KEY,
    full_name         TEXT NOT NULL,
    title             VARCHAR(128),
    graduate_undergrad VARCHAR(16),                -- 'UG','G'
    office_location   VARCHAR(128),
    phone_number      VARCHAR(32),
    website           TEXT
);

CREATE TABLE IF NOT EXISTS Career_Advisor (
    advisor_email       TEXT PRIMARY KEY,
    full_name           TEXT NOT NULL,
    title               VARCHAR(128),
    office_location     VARCHAR(128),
    phone_number        VARCHAR(32),
    website             TEXT,
    industry_specialty  VARCHAR(128),
    affiliated_departments TEXT,
    graduate_undergrad  VARCHAR(16)
);

/* 2-E  Additional Opportunities */
CREATE TABLE IF NOT EXISTS Additional_Opportunities (
    opportunity_name        TEXT PRIMARY KEY,
    opportunity_type        VARCHAR(64),
    opportunity_description TEXT,
    contact_info            TEXT,
    location                TEXT,
    prerequisites           TEXT,
    opportunity_url         TEXT,
    membership_requirements TEXT
);

/* 2-F  Conversation logs */
CREATE TABLE IF NOT EXISTS Conversation_History (
    log_id          SERIAL PRIMARY KEY,
    user_id         INT REFERENCES Users_Students(user_id) ON DELETE CASCADE,
    timestamp       TIMESTAMPTZ DEFAULT now(),
    query_text      TEXT,
    response_text   TEXT,
    feedback_rating VARCHAR(16)
);

/* ---------- ❸ RELATIONSHIPS / JUNCTIONS ------------------------ */

/* Student progress */
CREATE TABLE IF NOT EXISTS User_Course (
    user_id       INT REFERENCES Users_Students(user_id) ON DELETE CASCADE,
    course_id     VARCHAR(16) REFERENCES Courses(course_id)      ON DELETE CASCADE,
    semester_taken VARCHAR(16),
    grade         VARCHAR(8),
    status        VARCHAR(16),
    PRIMARY KEY (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS User_Program (             -- enrolment in a specific offering
    user_id      INT REFERENCES Users_Students(user_id)    ON DELETE CASCADE,
    program_id   VARCHAR(16) REFERENCES Program_Offerings(program_id) ON DELETE CASCADE,
    start_date   DATE,
    end_date     DATE,
    status       VARCHAR(16),
    PRIMARY KEY (user_id, program_id)
);

/* New: student’s membership in resources */
CREATE TABLE IF NOT EXISTS User_Resource (
    user_id          INT  REFERENCES Users_Students(user_id) ON DELETE CASCADE,
    opportunity_name TEXT REFERENCES Additional_Opportunities(opportunity_name)
                           ON DELETE CASCADE,
    membership_date  DATE,
    role             VARCHAR(32),
    PRIMARY KEY (user_id, opportunity_name)
);

/* Program composition (as in the ERD) */
CREATE TABLE IF NOT EXISTS Program_Course (
    program_id     VARCHAR(16) REFERENCES Program_Offerings(program_id) ON DELETE CASCADE,
    course_id      VARCHAR(16) REFERENCES Courses(course_id)            ON DELETE CASCADE,
    is_core        BOOLEAN,
    recommended_year INT,
    PRIMARY KEY (program_id, course_id)
);

CREATE TABLE IF NOT EXISTS Program_Resource (
    program_id       VARCHAR(16) REFERENCES Program_Offerings(program_id) ON DELETE CASCADE,
    opportunity_name TEXT         REFERENCES Additional_Opportunities(opportunity_name)
                                   ON DELETE CASCADE,
    notes            TEXT,
    PRIMARY KEY (program_id, opportunity_name)
);

/* Skills */
CREATE TABLE IF NOT EXISTS Course_Skill (
    course_id      VARCHAR(16) REFERENCES Courses(course_id) ON DELETE CASCADE,
    skill_id       INT REFERENCES Skills(skill_id)   ON DELETE CASCADE,
    coverage_level VARCHAR(16),
    PRIMARY KEY (course_id, skill_id)
);

CREATE TABLE IF NOT EXISTS Job_Skill (
    job_id         INT REFERENCES Job_Postings(job_id) ON DELETE CASCADE,
    skill_id       INT REFERENCES Skills(skill_id)     ON DELETE CASCADE,
    importance_level VARCHAR(16),
    PRIMARY KEY (job_id, skill_id)
);

/* Advisor relationships */
CREATE TABLE IF NOT EXISTS Academic_Advisor_Student (
    advisor_email TEXT REFERENCES Academic_Advisor(advisor_email) ON DELETE CASCADE,
    user_id       INT  REFERENCES Users_Students(user_id)       ON DELETE CASCADE,
    start_date    DATE,
    PRIMARY KEY (advisor_email, user_id)
);

CREATE TABLE IF NOT EXISTS Career_Advisor_Job (
    advisor_email TEXT REFERENCES Career_Advisor(advisor_email) ON DELETE CASCADE,
    job_id        INT  REFERENCES Job_Postings(job_id)          ON DELETE CASCADE,
    reason        TEXT,
    date_recommended TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (advisor_email, job_id)
);

CREATE TABLE IF NOT EXISTS Career_Advisor_Opportunity (
    advisor_email    TEXT REFERENCES Career_Advisor(advisor_email) ON DELETE CASCADE,
    opportunity_name TEXT REFERENCES Additional_Opportunities(opportunity_name) ON DELETE CASCADE,
    recommendation_reason TEXT,
    priority_level   VARCHAR(16),
    date_linked      DATE,
    PRIMARY KEY (advisor_email, opportunity_name)
);

/* ---------- ❹ RANK-ONLY ALIGNMENTS ----------------------------- */

CREATE TABLE IF NOT EXISTS Course_Category_Rank (
    category_id  VARCHAR(16) REFERENCES Category(category_id) ON DELETE CASCADE,
    course_id    VARCHAR(16)     REFERENCES Courses(course_id)    ON DELETE CASCADE,
    rank_pos     INT,
    alignment_dt TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (category_id, course_id)
);

/* ---------- ❺ INDEXES FOR COMMON QUERIES ----------------------- */

CREATE INDEX IF NOT EXISTS idx_rank_cat_pos ON Course_Category_Rank(category_id, rank_pos);
CREATE INDEX IF NOT EXISTS idx_rank_course  ON Course_Category_Rank(course_id);


/* ===============================================================
   End of schema
   =============================================================== */
